include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(Group9_Gossetti_Abdelrahman_Assignment_default_library_list )

# Handle files with suffix s, for group default-XC16
if(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_assemble)
add_library(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemble OBJECT ${Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_assemble})
    Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemble_rule(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemble)
    list(APPEND Group9_Gossetti_Abdelrahman_Assignment_default_library_list "$<TARGET_OBJECTS:Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemble>")

endif()

# Handle files with suffix S, for group default-XC16
if(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_assemblePreproc)
add_library(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemblePreproc OBJECT ${Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_assemblePreproc})
    Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemblePreproc_rule(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemblePreproc)
    list(APPEND Group9_Gossetti_Abdelrahman_Assignment_default_library_list "$<TARGET_OBJECTS:Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_assemblePreproc>")

endif()

# Handle files with suffix c, for group default-XC16
if(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_compile)
add_library(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_compile OBJECT ${Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_compile})
    Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_compile_rule(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_compile)
    list(APPEND Group9_Gossetti_Abdelrahman_Assignment_default_library_list "$<TARGET_OBJECTS:Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_compile>")

endif()

# Handle files with suffix s, for group default-XC16
if(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_dependentObject)
add_library(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_dependentObject OBJECT ${Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_dependentObject})
    Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_dependentObject_rule(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_dependentObject)
    list(APPEND Group9_Gossetti_Abdelrahman_Assignment_default_library_list "$<TARGET_OBJECTS:Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_dependentObject>")

endif()

# Handle files with suffix elf, for group default-XC16
if(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_bin2hex)
add_library(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_bin2hex OBJECT ${Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_bin2hex})
    Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_bin2hex_rule(Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_bin2hex)
    list(APPEND Group9_Gossetti_Abdelrahman_Assignment_default_library_list "$<TARGET_OBJECTS:Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_bin2hex>")

endif()


# Main target for this project
add_executable(Group9_Gossetti_Abdelrahman_Assignment_default_image_ab2XKVTn ${Group9_Gossetti_Abdelrahman_Assignment_default_library_list})

set_target_properties(Group9_Gossetti_Abdelrahman_Assignment_default_image_ab2XKVTn PROPERTIES
    OUTPUT_NAME "default"
    SUFFIX ".elf"
    RUNTIME_OUTPUT_DIRECTORY "${Group9_Gossetti_Abdelrahman_Assignment_default_output_dir}")
target_link_libraries(Group9_Gossetti_Abdelrahman_Assignment_default_image_ab2XKVTn PRIVATE ${Group9_Gossetti_Abdelrahman_Assignment_default_default_XC16_FILE_TYPE_link})

# Add the link options from the rule file.
Group9_Gossetti_Abdelrahman_Assignment_default_link_rule( Group9_Gossetti_Abdelrahman_Assignment_default_image_ab2XKVTn)

# Call bin2hex function from the rule file
Group9_Gossetti_Abdelrahman_Assignment_default_bin2hex_rule(Group9_Gossetti_Abdelrahman_Assignment_default_image_ab2XKVTn)

